import type { ImportExportModule } from './validationService';

const column = (key: string, label: string, required = false, statuses?: readonly string[], aliases?: readonly string[]) => ({ key, label, required, statuses, aliases });

export const IMPORT_EXPORT_MODULES = {
  Units: { key: 'units', label: 'Units', collectionName: 'units', idField: 'unit_id', roomField: 'room_number', columns: [column('unit_id', 'Unit ID', true), column('building', 'Building', true), column('floor', 'Floor', true), column('room_number', 'Room Number', true), column('owner_name', 'Owner Name'), column('resident_name', 'Resident Name'), column('phone', 'Phone'), column('status', 'Status', true, ['Active', 'Inactive'])] },
  ParkingCards: { key: 'parking-cards', label: 'Parking Cards', collectionName: 'parkingCards', idField: 'card_number', columns: [column('card_number', 'Card Number', true, undefined, ['card_id', 'Card ID']), column('card_type', 'Card Type', false, ['Temporary', 'VIP', 'Resident', 'Contractor', 'Staff', 'Other'], ['Card_Type']), column('qr_code_value', 'QR Code', false, undefined, ['qr_code', 'QR_Code', 'QR Code Value']), column('status', 'Status', false, ['Available', 'InUse', 'Disabled', 'Lost', 'Cancelled', 'Retired', 'Replaced'], ['status']), column('note', 'Note', false, undefined, ['Remark', 'remark'])] },
  Operators: { key: 'operators', label: 'Operators', collectionName: 'operators', idField: 'operator_id', columns: [column('operator_id', 'Operator ID', true), column('username', 'Username', true), column('operator_name', 'Operator Name', true), column('role', 'Role', true, ['Guard', 'ShiftHead', 'Manager', 'Admin']), column('shift', 'Shift'), column('phone', 'Phone'), column('site_id', 'Site', true), column('status', 'Status', true, ['Active', 'Inactive'])] },
  Keys: { key: 'keys', label: 'Keys', collectionName: 'keys', idField: 'key_id', roomField: 'room_number', columns: [column('key_id', 'Key ID', true), column('room_number', 'Room Number', true), column('key_type', 'Key Type', true), column('key_label', 'Key Label', true), column('status', 'Status', true, ['ว่าง', 'ถูกเบิก', 'Inactive']), column('note', 'Note')] },
  Blacklist: { key: 'blacklist', label: 'Blacklist', collectionName: 'blacklist', idField: 'blacklist_id', columns: [column('blacklist_id', 'Blacklist ID', true), column('type', 'Type', true, ['ทะเบียนรถ', 'เลขบัตรประชาชน', 'ชื่อบุคคล']), column('vehicle_plate', 'Vehicle Plate'), column('id_card_number', 'ID Card Number'), column('name', 'Name'), column('reason', 'Reason', true), column('severity', 'Severity', true, ['เตือนภัยระดับต่ำ', 'ห้ามเข้าเด็ดขาด', 'เฝ้าระวังพิเศษ']), column('status', 'Status', true, ['Active', 'Inactive'])] },
  VehicleLogs: { key: 'vehicle-logs', label: 'Vehicle Logs', collectionName: 'vehicleLogs', idField: 'log_id', columns: [column('log_id', 'Log ID', true), column('vehicle_plate', 'Vehicle Plate', true), column('visitor_name', 'Visitor Name'), column('target_room', 'Target Room'), column('entry_time', 'Entry Time', true), column('exit_time', 'Exit Time'), column('status', 'Status')] },
  ContractorLogs: { key: 'contractor-logs', label: 'Contractor Logs', collectionName: 'contractorLogs', idField: 'contractor_log_id', columns: [column('contractor_log_id', 'Log ID', true), column('contractor_name', 'Contractor Name', true), column('company', 'Company'), column('target_room', 'Target Room'), column('entry_time', 'Entry Time', true), column('exit_time', 'Exit Time'), column('status', 'Status')] },
  PatrolLogs: { key: 'patrol-logs', label: 'Patrol Logs', collectionName: 'patrolLogs', idField: 'patrol_log_id', columns: [column('patrol_log_id', 'Log ID', true), column('point_name', 'Point Name', true), column('guard_name', 'Guard Name', true), column('checkin_time', 'Check-in Time', true), column('status', 'Status')] },
  KeyLogs: { key: 'key-logs', label: 'Key Logs', collectionName: 'keyLogs', idField: 'key_log_id', roomField: 'room_number', columns: [column('key_log_id', 'Log ID', true), column('room_number', 'Room Number', true), column('borrower_name', 'Borrower Name', true), column('checkout_time', 'Checkout Time', true), column('return_time', 'Return Time'), column('status', 'Status')] },
  IncidentReports: { key: 'incident-reports', label: 'Incident Reports', collectionName: 'incidentReports', idField: 'incident_id', columns: [column('incident_id', 'Incident ID', true), column('incident_datetime', 'Incident Date Time', true), column('location', 'Location', true), column('incident_type', 'Incident Type', true), column('description', 'Description', true), column('status', 'Status'), column('severity', 'Severity')] },
} satisfies Record<string, ImportExportModule>;

export type ImportExportModuleName = keyof typeof IMPORT_EXPORT_MODULES;
