import { useState, type FormEvent } from 'react';
import type { ParkingCardRecord } from '../types';

export interface ParkingCardActionValues {
  card_number: string; qr_code_value: string; card_type: ParkingCardRecord['card_type']; status: ParkingCardRecord['status']; note: string; reason: string;
}

export default function ParkingCardActionDialog({ mode, card, onClose, onSubmit }: { mode: 'edit' | 'replace'; card: ParkingCardRecord; onClose: () => void; onSubmit: (values: ParkingCardActionValues) => Promise<void> }) {
  const [values, setValues] = useState<ParkingCardActionValues>({ card_number: mode === 'edit' ? card.card_number : '', qr_code_value: mode === 'edit' ? card.qr_code_value : '', card_type: mode === 'edit' ? card.card_type : 'Temporary', status: mode === 'edit' ? card.status : 'Available', note: mode === 'edit' ? card.note || '' : `Replacement for ${card.card_number}`, reason: '' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await onSubmit(values); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[95] flex items-center justify-center bg-black/75 p-3" onMouseDown={onClose}><form role="dialog" aria-modal="true" aria-label={mode === 'edit' ? `Edit ${card.card_number}` : `Replace ${card.card_number}`} onSubmit={submit} onMouseDown={event => event.stopPropagation()} className="w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-950 p-5"><h3 className="font-black text-white">{mode === 'edit' ? `Edit Card ${card.card_number}` : `Replace Card ${card.card_number}`}</h3><p className="mb-4 text-xs text-slate-400">Site: {card.site_id || 'Missing Site — migrate before management'}</p><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{[['card_number', 'Card Number *'], ['qr_code_value', 'QR Code'], ['note', 'Remark']].map(([key, label]) => <label key={key} className="text-xs font-bold text-slate-400">{label}<input required={key === 'card_number'} value={String(values[key as keyof ParkingCardActionValues])} onChange={event => setValues(current => ({ ...current, [key]: event.target.value }))} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-white" /></label>)}<label className="text-xs font-bold text-slate-400">Card Type *<select value={values.card_type} onChange={event => setValues(current => ({ ...current, card_type: event.target.value as ParkingCardRecord['card_type'] }))} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-white">{['Temporary', 'Resident', 'Contractor', 'Staff', 'Other'].map(type => <option key={type}>{type}</option>)}</select></label>{mode === 'edit' && <label className="text-xs font-bold text-slate-400">Status<select value={values.status} onChange={event => setValues(current => ({ ...current, status: event.target.value as ParkingCardRecord['status'] }))} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-white">{['Available', 'Disabled', 'Suspended', 'Lost'].map(status => <option key={status}>{status}</option>)}</select></label>}{mode === 'replace' && <label className="text-xs font-bold text-slate-400 sm:col-span-2">Replacement Reason *<textarea required value={values.reason} onChange={event => setValues(current => ({ ...current, reason: event.target.value }))} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-white" /></label>}</div>{error && <p className="mt-3 rounded-lg bg-red-950 p-3 text-xs text-red-300">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl bg-slate-800 px-4 py-2 text-xs font-bold text-white">Cancel</button><button disabled={busy || !card.site_id} className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy ? 'Saving...' : mode === 'edit' ? 'Save Changes' : 'Issue Replacement'}</button></div></form></div>;
}
